version: "2.1"
services:
  readarr:
    image: linuxserver/readarr:latest
    container_name: readarr
    environment:
      - PUID=1000          # Your user ID
      - PGID=1000          # Your group ID
      - TZ=Africa/Nairobi  # Your timezone
    volumes:
      - ./config:/config               # Config folder
      - /home/minos/audiobooks:/tv          # TV shows directory
      - /home/minos/Downloads:/downloads  # Downloads directory
    ports:
      - 8989:8989                      # Web UI port
    restart: unless-stopped



